pipeline {
    agent any
    stages {
        stage ('cloning'){ 
            steps {
            git branch: 'lakshman', url: 'https://github.com/lakshman-cpu/jenkins'

            }
        }
        stage('merge')
        {
            steps {
                withCredentials([usernamePassword(credentialsId: 'bf376d7d-1a46-4e24-b890-40381da0fae8', 
                                                 usernameVariable: 'GIT_USER', 
                                                 passwordVariable: 'GIT_TOKEN')]) {
                sh ''' 
                git init 
                git remote -v 
                git remote remove origin
                git remote set-url origin "https://${GIT_USER}:${GIT_TOKEN}@://github.com/lakshman-cpu/jenkins"
                git config --global user.name "lakshman"
                git config --global user.email "lakshmankommineni1@gmail.com"
                git push origin lucky
                '''
                                                }

            }
        }
    }
}