pipeline {
    agent any
    stages {
        stage ('cloning'){ 
            steps {
            git branch: 'lakshman', url: 'https://github.com/lakshman-cpu/jenkins'

            }
        }
        stage('merge')
        {
            steps {
                sh ''' 
                git init 
                git remote -v 
                git remote remove origin
                git remote add origin https://github.com/lakshman-cpu/jenkins
                git config --global user.name "lakshman"
                git config --global user.email "lakshmankommineni1@gmail.com"
                git push origin lucky
                '''

            }
        }
    }
}