pipeline {
    agent any 

    stages {
        stage('clone'){
            steps {
            git branch: 'lakshman', url: 'https://github.com/lakshman-cpu/jenkins'
            }
        }

        stage('docker image'){
            agent {
                docker { image 'python:latest'}
            }
            steps {
                sh '''python3 --version'''
            }
        }
    }
}